### ISSUE TITLE
Unable to create multiple edges between two nodes

### ISSUE THREAD

**Issue by jschomay** [elm-community/graph#11]
I have been using this library in a few projects, and I have had the need to create multiple relationships between nodes.  However, due to the fact that NodeContext's outgoing and incoming Adjacency's are IntDicts, if I try to create more than one edge between two nodes, it simply overwrites the value at that key instead of adding a new edge.

Multiple edges between nodes seems to be a reasonable and normal feature of a graph, so I would like a way to accomplish this.  At present, I had to make my edges into Lists to indicate multiple relationships, but that is clunky to use.  I am not sure what alternate data structure to suggest besides a regular list, or giving edges unique ids regardless of their from and to nodes.  Maybe you have a better solution.

Thank you for considering this request.

**Comment by sgraf812** [comment]
I think using lists (or any other appropriate monoid) as edge labels is the way to handle that.

Making it so that `incoming : IntDict (List Edge)` is quite annoying for the general case and is only marginally better than mapping each `Edge (List label)` to `List (Edge label)` at each use site.
