### ISSUE TITLE
Edge insertion

### ISSUE THREAD

**Issue by hsuominen** [elm-community/graph#19]
Is there any particular design decision as to why no edge insertion operation is implemented? Just wanted to check before figuring out how this would best be done and hopefully opening a PR.

**Comment by sgraf812** [comment]
I think you can derive this from [`update`](https://package.elm-lang.org/packages/elm-community/graph/latest/Graph#update) (unchecked): 

```
insertEdge fromNode lbl toNode graph =
    update fromId (\maybeCtx -> case maybeCtx of Nothing -> Nothing; Just ctx -> { ctx | outgoing = IntDict.insert toNode lbl ctx.outgoing }) graph
```

Is this too complicated? It's hard to tell how 'inserting an edge' is defined, really: What if its start or end node wasn't part of the graph before? Should we also insert the respective start and end nodes or just do nothing? Using `update` has the boon of being rather explicit about this.

EDIT: Well, or not: the above definition will insert an edge iff the `fromNode` is present, regardless of whether `toNode` already exists in the graph (and will create it if it wasn't present).

**Comment by Libbum** [comment]
A more formal (and checked) implementation:

```elm
insertEdge : Edge e -> Graph n e -> Graph n e
insertEdge edge =
    update edge.from
        (\maybeCtx ->
            case maybeCtx of
                Nothing ->
                    Nothing

                Just ctx ->
                    Just { ctx | outgoing = IntDict.insert edge.to edge.label ctx.outgoing }
        )
```

**Comment by sgraf812** [comment]
I don't follow. How is this better than what I sketched above? It seems `yourInsertEdge edge = myInsertEdge edge.from edge.label edge.to`. 

It still has the same drawbacks: It's pretty much unclear what should happen if either `edge.from` or `edge.to` is not already in the graph. Should the respective nodes be added or not? Our implementation would always add an edge if `edge.from` is present in the graph, whereas it's irrelevant if `edge.to` is in the graph or not. That's utterly asymmetrical. If we would support such an operation, then either we insert the edge

1. Only iff both `edge.to` and `edge.from` are present in the graph
2. Regardless of which of the nodes is in the graph. If either source or target isn't present, we simultaneously insert a new node with just that edge.

We *could* add any of the two or both, but they'd have to be documented accordingly. Also the value over just explicitly crafting such a function from `update` (which would communicate the intent) when needed isn't really clear to me.

**Comment by Libbum** [comment]
I didn't mean better at all, just that you had said you didn't check it. So `fromId` is not found and the `Just ctx` branch doesn't return a `Maybe`. The only changes I really made in that case was to formalise the type signature such that it aligns with the package: Edges are `from, to, label` rather than `from, label, to`.

I agree that it's probably not necessary to include it as a function in the package, hence the comment here rather than a PR with more complete docs etc. Just a message for @hsuominen in-case they were struggling with the implementation.

**Comment by sgraf812** [comment]
Right, thanks. Upon re-reading my comment above it sounds a lot more snarky than I intended it to, sorry for that. I'd say we close this until someone with a compelling reason drops by.

**Comment by hsuominen** [comment]
Thanks for the input @sgraf812 (and follow up @Libbum) helped steer me in the right direction. Considering that fact that probably the default case on what to do if from/to don't exist in the graph is specific to the use case I agree it may make sense to leave this out of the api. Hopefully the next person that stumbles on this question finds this thread.
