### ISSUE TITLE
Update to elm 0.18

### ISSUE THREAD

**Issue by jhrcek** [elm-community/graph#2]
Could you please update this for elm 0.18?

**Comment by mgold** [comment]
The dependencies `imeckler/queue` and `evancz/focus` will need to be updated first. I know that Evan has said that focus is a possible antipattern, so the fact that it is not updated is likely deliberate.

**Comment by sgraf812** [comment]
Yeah, I'm currently thinking about options for an upgrade.

I think I could just copy and paste `imeckler/queue` into an internal module, but doing the same for `evancz/focus` is pretty much pointless without also offering it as a separate package.

I find using foci for this library pretty elegant, as it cuts out some repetition in update tasks. Totally don't understand the argument about being an anti-pattern, seems like premature optimization. Also that's no reason to just discontinue a library, but whatever.

So, I think there are two options to move this forward: Get rid of all focus related stuff or fork `evancz/focus`. Any opinions?

**Comment by mgold** [comment]
If focuses are not crucial to the module or its public interface, I'm thinking it should be rewritten without them.

**Comment by sgraf812** [comment]
Fixed in https://github.com/elm-community/graph/commit/d3b225e26642fc7c5b89196b05ae5d85661c04f2.
