### ISSUE TITLE
heightLevels accepts graphs with cycles

### ISSUE THREAD

**Issue by DavidDTA** [elm-community/graph#9]
This is related to #4.

`heightLevels` is another function whose result doesn't make sense if the graph has cycles.  I think the signature of `heightLevels` should be a result like `topologicalSort`.

**Comment by sgraf812** [comment]
Alright, I redesigned stuff around an [`AcyclicGraph`](https://github.com/elm-community/graph/blob/7ac05a8facc7645d925da8d83f0603af6cc84719/src/Graph.elm#L722-L791) abstraction that is returned by a new `checkAcyclic` function and also by `stronglyConnectedComponents`. This can be passed to `topologicalSort` and `heightLevels`, making them total.

Does this work for you? If so, I'll make a release to get this out.

**Comment by DavidDTA** [comment]
That sounds like a good way of handling it to me.
